---
- name: install python3 with apt
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - python3
    - python3-pip

- name: ensure local python3 pips are in path
  lineinfile:
    path: "{{ dotfile }}"
    state: present
    line: "[[ \":$PATH:\" != *\":$HOME/.local/bin:\"* ]] && PATH=\"$HOME/.local/bin:$PATH\" || true"
