---
# This pup is not responsible for installing Python.
- name: determine if python installed
  command: which python
  changed_when: no

- name: determine if pip installed
  command: which pip
  changed_when: no

- name: install pip packages
  include_tasks: pip_packages.yml
