---
# This pup is not responsible for installing Python.
- name: determine if python installed
  command: which python && which pip
  register: python_is_installed
  changed_when: no

- name: install pip packages
  include_tasks: pip_packages.yml
