---
- name: install python2 pips
  pip:
    name: "{{ item }}"
    executable: pip2
  with_items: "{{ pip2_to_install }}"

- name: uninstall python2 pips
  pip:
    name: "{{ item }}"
    state: absent
    executable: pip2
  with_items: "{{ pip2_to_uninstall }}"

- name: install python3 pips
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items: "{{ pip3_to_install }}"

- name: uninstall python3 pips
  pip:
    name: "{{ item }}"
    state: absent
    executable: pip3
  with_items: "{{ pip3_to_uninstall }}"

